## NumPy
By B11901018
<br>
source:
__[source 1](https://ithelp.ithome.com.tw/articles/10251661)__
__[source 2](https://www.brilliantcode.net/1022/numpy-tutorial-basics-array-creations/)__

In [1]:
import numpy as np

### Intro & array
`.array` creates an array
<br>
`.dtype` is used to see the type of an array

In [2]:
array1 = np.array([0, 1, 2, 1, 0])
array2 = np.array([0, 1.5, 3, 1.5, 0])

print(array1, "\ntype =", type(array1), array1.dtype)
print(array2, "\ntype =", type(array2), array2.dtype)

[0 1 2 1 0] 
type = <class 'numpy.ndarray'> int64
[0.  1.5 3.  1.5 0. ] 
type = <class 'numpy.ndarray'> float64


***
`.ndim` and `.shape` is used to see its dimension
<br>
`.size` shows number of elements in an array

In [3]:
array3 = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])
array4 = np.array([[[0, 1, 2], [1, 2, 3], [2, 3, 4]], [[10, 11, 12], [11, 12, 13], [12, 13, 14]]])

print(array3, "\ndimension =", array3.ndim, "\nsize of every dimension =", array3.shape, "\nsize =", array3.size)
print(array4, "\ndimension =", array4.ndim, "\nsize of every dimension =", array4.shape, "\nsize =", array4.size)

[[0 1 2]
 [1 2 3]
 [2 3 4]] 
dimension = 2 
size of every dimension = (3, 3) 
size = 9
[[[ 0  1  2]
  [ 1  2  3]
  [ 2  3  4]]

 [[10 11 12]
  [11 12 13]
  [12 13 14]]] 
dimension = 3 
size of every dimension = (2, 3, 3) 
size = 18


use `.reshape` to change the dimensions of an array
<br>
`ValueError` will be raised if its size doesn't match

In [4]:
array5 = np.array([0, 1, 2, 3, 4, 5])
array6 = array5.reshape((3, 2))

print("array5: \n", array5)
print("array6: \n", array6)

array5: 
 [0 1 2 3 4 5]
array6: 
 [[0 1]
 [2 3]
 [4 5]]


In [5]:
array7 = array5.reshape((3, 3))
print("array7: \n", array7)

ValueError: cannot reshape array of size 6 into shape (3,3)

***
### Create
numpy can create an array automatically
<br><br>
`np.zeros` and `np.ones`
<br>
`x = np.zeros(count)` equals to `x = [0] * count`
<br>
`x = np.ones(count)` equals to `x = [1] * count`
<br><br>
`np.empty`
<br>
`x = np.empty(count)` equals to `x = [k] * count`
<br>
the only problem is that you don't know what k is (it just grabs data from memory)
<br><br>
`np.arange`
<br>
`x = np.arange(start, end, step)` equals to `x = [i for i in range(start, end, step)]`
<br><br>
`np.linspace`
<br>
`x = np.linspace(min, max, num)` equals to `x = [min + (max - min) * i / (num - 1) for i in range(1, num)]`
<br>
in other words, create an array with `num` elements between `min` and `max` (including both)
<br>
to "not include" `max`: `x = np.linspace(min, max, num, endpoint=False)`
<br><br>
(well, it's actually different types: "**array**" vs "**list**")
<br>
to make it easier to read, arrays are printed as lists below

In [6]:
a1 = np.zeros(10)
a2 = np.ones(10) * 5
a3 = np.empty(15)
a4 = np.arange(10)
a5 = np.arange(0, 10, 2)
a6 = np.linspace(0, 10, 11)
a7 = np.linspace(0, 10, 5, endpoint=False)

print("a1: ", list(a1))
print("a2: ", list(a2))
print("a3: ", list(a3))
print("a4: ", list(a4))
print("a5: ", list(a5))
print("a6: ", list(a6))
print("a7: ", list(a7))

a1:  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
a2:  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
a3:  [2.39504685e-316, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
a4:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a5:  [0, 2, 4, 6, 8]
a6:  [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
a7:  [0.0, 2.0, 4.0, 6.0, 8.0]


note that `np.zeros`, `np.ones`, `np.linspace` creates array with `float` data;
<br>
`np.arange` creates array with int data if start, end, step are all `int`
<br><br>
use `.dtype` to change data type:
`dtype=np.int16`: change to int; `dtype=np.int16`: change to float

In [7]:
a8 = np.ones(10) * 5
a9 = np.ones(10, dtype=np.int16) * 5
a10 = np.ones(10, dtype=np.float16) * 5

print("a8: ", list(a8))
print("a9: ", list(a9))
print("a10: ", list(a10))

a8:  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
a9:  [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
a10:  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]


***
### Calculation
arrays can be calculated or edited as a variable
<br>`x = np.arange(N) + 1` equals to `x = [i + 1 for i in range(N)]`

In [8]:
x = np.arange(10)
x1 = x + 1
x2 = x * 2
x3 = x % 3
x4 = x1 + x2
x5 = x1 * x2

print("x+1: ", list(x1))
print("x*2: ", list(x2))
print("x%3: ", list(x3))
print()
print("x1 + x2: ", list(x4))
print("x1 * x2: ", list(x5))

x+1:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
x*2:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
x%3:  [0, 1, 2, 0, 1, 2, 0, 1, 2, 0]

x1 + x2:  [1, 4, 7, 10, 13, 16, 19, 22, 25, 28]
x1 * x2:  [0, 4, 12, 24, 40, 60, 84, 112, 144, 180]


***
### Boolean array
a numpy array can be seen as a variable, so using boolean (comparisons) will return a new array of `True` and `False`

In [9]:
x = np.arange(10)
y = x % 2 == 0

print("x: ", x)
print("is even: ", y)

x:  [0 1 2 3 4 5 6 7 8 9]
is even:  [ True False  True False  True False  True False  True False]


what can boolean arrays do?
<br>
filter!
***
### Replacement
replace value below/above value: `np.clip`, `np.maximum`, `np.minimum`
<br>
replace with condition: `array[condition] = new_value` (this overwrites original array)
<br>

In [10]:
x = np.arange(10)
x1 = np.clip(x, 1, 8)
x2 = np.maximum(x, 5)
x3 = np.minimum(x, 3)

print("x1: ", x1)
print("x2: ", x2)
print("x3: ", x3)

x1:  [1 1 2 3 4 5 6 7 8 8]
x2:  [5 5 5 5 5 5 6 7 8 9]
x3:  [0 1 2 3 3 3 3 3 3 3]


In [11]:
x = np.arange(10)
y = x%2 == 0
x[x%2 == 0] = 0 # changes x

print(y)
print(x)

[ True False  True False  True False  True False  True False]
[0 1 0 3 0 5 0 7 0 9]


***
### Indexing and slicing
similiar to list indexing and slicing, but you can assign (change) the value

In [12]:
x = np.arange(10)
x1 = x[::-1]
x2 = x[:5]

print("x: ", x)
print("reverse: ", x1)
print("first half: ", x2)

x:  [0 1 2 3 4 5 6 7 8 9]
reverse:  [9 8 7 6 5 4 3 2 1 0]
first half:  [0 1 2 3 4]


In [13]:
x = np.arange(10)
print(x)
x[3:6] = 0
print(x)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 0 0 0 6 7 8 9]


moreover, you can use arrays as indices

In [14]:
x = np.arange(10) ** 2
y = np.arange(0, 10, 2)

print("x: ", x)
print("y: ", y)
print("x[y]: ", x[y])

x:  [ 0  1  4  9 16 25 36 49 64 81]
y:  [0 2 4 6 8]
x[y]:  [ 0  4 16 36 64]


***
### Functions
arrays can be changed by a np function
<br>
`x = np.sin(np.arange(N))` equals to `x = [math.sin(i) for i in range(N)]`
<br>
(note: there's quite a lot of interesting things about `np.set_printoptions`, but that's just for printing and not necessary to know
)

In [15]:
np.set_printoptions(suppress=True, precision=3) # just to change its printing styles
a1 = np.sin(np.arange(10) * np.pi / 6)
a2 = np.exp2(np.arange(10))
a3 = np.sqrt(np.arange(10))
a4 = np.floor(a3)

print("sin 0 ~ sin 3π/2:\n", a1)
print("2^0 ~ 2^9:\n", a2)
print("√0 ~ √9:\n", a3)
print("［a3］:\n", a4)

sin 0 ~ sin 3π/2:
 [ 0.     0.5    0.866  1.     0.866  0.5    0.    -0.5   -0.866 -1.   ]
2^0 ~ 2^9:
 [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
√0 ~ √9:
 [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
［a3］:
 [0. 1. 1. 1. 2. 2. 2. 2. 2. 3.]


numpy has sort functions

In [16]:
x = np.array([[1, 5, 2, 19, 15, 0, 2, 5, 7, 114], [18, 3, 2, 5, 5, 2, 6, 5, 67, -1]])

print("original:\n", x)
print("sorted:\n", np.sort(x))
print("index of sorted array:\n", np.argsort(x))

original:
 [[  1   5   2  19  15   0   2   5   7 114]
 [ 18   3   2   5   5   2   6   5  67  -1]]
sorted:
 [[  0   1   2   2   5   5   7  15  19 114]
 [ -1   2   2   3   5   5   5   6  18  67]]
index of sorted array:
 [[5 0 2 6 1 7 8 4 3 9]
 [9 2 5 1 3 4 7 6 0 8]]


***
### Statistical functions
`np.max`, `np.min`, `np.sum`, `np.prod`, `np.mean`, `np.cumsum`, `np.std`, `np.var`, `np.median`, `np.percentile`, `np.ptp`, etc.

In [17]:
x = np.arange(1, 11)
x1 = x.min()
x2 = x.max()
x3 = x.sum()
x4 = x.prod()
x5 = x.mean()
x6 = x.cumsum()

print("x: ", x)
print("min: ", x1)
print("max: ", x2)
print("sum: ", x3)
print("product: ", x4)
print("mean: ", x5)
print("cumulative sum: ", x6)

x:  [ 1  2  3  4  5  6  7  8  9 10]
min:  1
max:  10
sum:  55
product:  3628800
mean:  5.5
cumulative sum:  [ 1  3  6 10 15 21 28 36 45 55]


the functions written above can be called from np, for example:
<br>
`x1 = x.min()` equals to `x1 = np.min(x)`
<br><br>
however, `np.median` can only be called from np, i.e., `x1 = x.median()` won't work
<br>
the same goes to some other functions, but that's too detailed and can be ignored here

In [18]:
x = np.arange(1, 11)
x1 = x.std()
x2 = x.var()
x3 = np.median(x)

print("x: ", x)
print("standard deviation (σ): ", x1)
print("variance (var): ", x2)
print("median (m): ", x3)

x:  [ 1  2  3  4  5  6  7  8  9 10]
standard deviation (σ):  2.8722813232690143
variance (var):  8.25
median (m):  5.5


***
### Matrix functions
matrixs are usually 2-d, but numpy supports any dimensions (mostly, I guess)

In [19]:
x = np.array([[0, 1], [2, 3]])
t = x.T
r = x.ravel()

print("original:\n", x)
print("transpose:\n", t)
print("flattened:\n", r)

original:
 [[0 1]
 [2 3]]
transpose:
 [[0 2]
 [1 3]]
flattened:
 [0 1 2 3]


In [20]:
i2 = np.eye(2)
i3 = np.eye(3)

print("2*2 i:\n", i2)
print("3*3 i:\n", i3)

2*2 i:
 [[1. 0.]
 [0. 1.]]
3*3 i:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


stacking and splitting: `np._stack`, `np._split`, where `_` is h for horizontal and v for vertical
<br>
note that splitting an array makes a **list** of splitted **array**

In [21]:
x = np.array([[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]])
h_stack = np.hstack((x, x))
v_stack = np.vstack((x, x))
h_split = np.hsplit(x, 3)
v_split = np.vsplit(x, 2)

print("original:\n", x)
print("horizontal stacking:\n", h_stack)
print("vertical stacking:\n", v_stack)
print("horizontal splitting:")
for i in h_split:
	print(i)
print("vertical splitting:")
for j in v_split:
	print(j)

original:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
horizontal stacking:
 [[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]]
vertical stacking:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
horizontal splitting:
[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]
vertical splitting:
[[0 1 2 3 4 5]]
[[ 6  7  8  9 10 11]]


***
### Random functions
(not *random* functions of numpy, but functions that generates random numbers)
<br>
`np.random.rand(shape)`: array of `shape` filled with random floats between 0 and 1
<br>
`np.random.random(num)`: `num` random floats between 0 and 1
<br>
`np.random.randint(min, max, num)`: `num` random integers between `min` and `max` (not include `max - 1`)
<br>
`np.random.choice(range, num, replace)`: `num` random integers between `0` and `range` (not include `range - 1`), doesn't repeat if `replace=False`

In [22]:
print("rand, shape = (2):\n",np.random.rand(2))
print("rand, shape = (3, 2):\n",np.random.rand(3, 2))
print("random, num = 3:\n",np.random.random(3))
print("randint, range = 10~61, num = 10:\n", np.random.randint(60, 101, 10))
print("choice, range = 11, num = 10:, repeat = True\n", np.random.choice(11, 10, True))
print("choice, range = 11, num = 10:, repeat = False\n", np.random.choice(11, 10, False))

rand, shape = (2):
 [0.723 0.769]
rand, shape = (3, 2):
 [[0.129 0.634]
 [0.452 0.548]
 [0.093 0.478]]
random, num = 3:
 [0.609 0.742 0.255]
randint, range = 10~61, num = 10:
 [82 98 94 75 71 68 82 60 63 93]
choice, range = 11, num = 10:, repeat = True
 [0 3 6 1 2 4 4 1 7 2]
choice, range = 11, num = 10:, repeat = False
 [10  6  0  7  8  1  3  9  2  4]


***
#### End